/* eslint-disable */
import { FuseNavigationItem } from '@fuse/components/navigation';

export const defaultNavigation: FuseNavigationItem[] = [
    {
        id: 'home',
        title: 'nav.home',
        type: 'basic',
        icon: 'heroicons_outline:home',
        link: '/home',
    },
    {
        id: 'smart-check',
        title: 'nav.smart_check',
        type: 'collapsable',
        icon: 'heroicons_outline:sparkles',
        children: [
            {
                id: 'chat',
                title: 'nav.chat',
                subtitle: 'nav.ai_validation',
                type: 'basic',
                icon: 'heroicons_outline:chat-bubble-left-right',
                link: '/chat',
            },
            {
                id: 'postman',
                title: 'nav.postman',
                subtitle: 'nav.api_testing',
                type: 'basic',
                icon: 'heroicons_outline:command-line',
                link: '/postman',
            },
            {
                id: 'smart-batch',
                title: 'nav.smart_batch',
                subtitle: 'nav.batch_automation',
                type: 'basic',
                icon: 'heroicons_outline:queue-list',
                link: '/smart-batch',
            },
            {
                id: 'history',
                title: 'nav.history',
                subtitle: 'nav.history_subtitle',
                type: 'basic',
                icon: 'heroicons_outline:clock',
                link: '/history',
            },
            {
                type: 'divider',
            },
            {
                id: 'subscription-plans',
                title: 'nav.subscription_plans',
                subtitle: 'nav.manage_subscription',
                type: 'basic',
                icon: 'heroicons_outline:credit-card',
                link: '/subscription-plans',
            },
            {
                id: 'add-credits',
                title: 'nav.add_credits',
                subtitle: 'nav.purchase_credits',
                type: 'basic',
                icon: 'heroicons_outline:plus-circle',
                link: '/add-credits',
            },
        ],
    },
    {
        id: 'smart-enroll',
        title: 'nav.smart_enroll',
        type: 'collapsable',
        icon: 'heroicons_outline:document-magnifying-glass',
        children: [
            {
                id: 'smart-scan',
                title: 'nav.smart_scan',
                subtitle: 'nav.scan_documents',
                type: 'basic',
                icon: 'heroicons_outline:document-text',
                link: '/smart-enroll/smart-scan',
            },
            {
                id: 'smart-enroll-projects',
                title: 'nav.smart_enroll_projects',
                subtitle: 'nav.smart_enroll_projects_subtitle',
                type: 'basic',
                icon: 'heroicons_outline:rectangle-stack',
                link: '/smart-enroll/projects',
            },
            {
                id: 'smart-enroll-plans',
                title: 'nav.smart_enroll_plans',
                subtitle: 'nav.smart_enroll_plans_subtitle',
                type: 'basic',
                icon: 'heroicons_outline:receipt-percent',
                link: '/smart-enroll/plans',
            },
        ],
    },
    {
        id: 'smart-monitor',
        title: 'nav.smart_monitor',
        type: 'collapsable',
        icon: 'heroicons_outline:signal',
        children: [
            {
                id: 'status-check',
                title: 'nav.status_check',
                subtitle: 'nav.system_health',
                type: 'basic',
                icon: 'heroicons_outline:check-circle',
                link: '/smart-monitor/status-check',
            },
            {
                id: 'incidents',
                title: 'nav.incidents',
                subtitle: 'nav.active_incidents',
                type: 'basic',
                icon: 'heroicons_outline:exclamation-triangle',
                link: '/smart-monitor/incidents',
            },
            {
                id: 'webhooks',
                title: 'nav.webhooks',
                subtitle: 'nav.webhooks_subtitle',
                type: 'basic',
                icon: 'heroicons_outline:link',
                link: '/smart-monitor/webhooks',
            },
        ],
    },
    {
        id: 'smart-tools',
        title: 'nav.smart_tools',
        type: 'collapsable',
        icon: 'heroicons_outline:wrench-screwdriver',
        children: [
            {
                id: 'smart-reduce',
                title: 'nav.smart_reduce',
                subtitle: 'nav.resize_compress_images',
                type: 'basic',
                icon: 'heroicons_outline:photo',
                link: '/smart-tools/smart-reduce',
            },
        ],
    },
    // {
    //   id: 'zelf-id',
    //   title: 'Zelf ID',
    //   type: 'basic',
    //   icon: 'heroicons_outline:identification',
    //   link: '/zelf-id',
    // },
];

export const compactNavigation: FuseNavigationItem[] = [
    {
        id: 'chat',
        title: 'nav.chat',
        tooltip: 'nav.chat',
        type: 'aside',
        icon: 'heroicons_outline:chat-bubble-left-right',
        children: [],
    },
];

export const futuristicNavigation: FuseNavigationItem[] = [
    {
        id: 'chat',
        title: 'nav.chat',
        type: 'group',
        children: [],
    },
];

export const horizontalNavigation: FuseNavigationItem[] = [
    {
        id: 'home',
        title: 'nav.home',
        type: 'basic',
        icon: 'heroicons_outline:home',
        link: '/home',
    },
    {
        id: 'smart-check',
        title: 'nav.smart_check',
        type: 'collapsable',
        icon: 'heroicons_outline:sparkles',
        children: [
            {
                id: 'chat',
                title: 'nav.chat',
                subtitle: 'nav.ai_validation',
                type: 'basic',
                icon: 'heroicons_outline:chat-bubble-left-right',
                link: '/chat',
            },
            {
                id: 'postman',
                title: 'nav.postman',
                subtitle: 'nav.api_testing',
                type: 'basic',
                icon: 'heroicons_outline:command-line',
                link: '/postman',
            },
            {
                id: 'smart-batch',
                title: 'nav.smart_batch',
                subtitle: 'nav.batch_automation',
                type: 'basic',
                icon: 'heroicons_outline:queue-list',
                link: '/smart-batch',
            },
            {
                id: 'history',
                title: 'nav.history',
                subtitle: 'nav.history_subtitle',
                type: 'basic',
                icon: 'heroicons_outline:clock',
                link: '/history',
            },
            {
                type: 'divider',
            },
            {
                id: 'subscription-plans',
                title: 'nav.subscription_plans',
                subtitle: 'nav.manage_subscription',
                type: 'basic',
                icon: 'heroicons_outline:credit-card',
                link: '/subscription-plans',
            },
            {
                id: 'add-credits',
                title: 'nav.add_credits',
                subtitle: 'nav.purchase_credits',
                type: 'basic',
                icon: 'heroicons_outline:plus-circle',
                link: '/add-credits',
            },
        ],
    },
    {
        id: 'smart-enroll',
        title: 'nav.smart_enroll',
        type: 'collapsable',
        icon: 'heroicons_outline:document-magnifying-glass',
        children: [
            {
                id: 'smart-scan',
                title: 'nav.smart_scan',
                subtitle: 'nav.scan_documents',
                type: 'basic',
                icon: 'heroicons_outline:document-text',
                link: '/smart-enroll/smart-scan',
            },
            {
                id: 'smart-enroll-projects',
                title: 'nav.smart_enroll_projects',
                subtitle: 'nav.smart_enroll_projects_subtitle',
                type: 'basic',
                icon: 'heroicons_outline:rectangle-stack',
                link: '/smart-enroll/projects',
            },
            {
                id: 'smart-enroll-plans',
                title: 'nav.smart_enroll_plans',
                subtitle: 'nav.smart_enroll_plans_subtitle',
                type: 'basic',
                icon: 'heroicons_outline:receipt-percent',
                link: '/smart-enroll/plans',
            },
        ],
    },
    {
        id: 'smart-monitor',
        title: 'nav.smart_monitor',
        type: 'collapsable',
        icon: 'heroicons_outline:signal',
        children: [
            {
                id: 'status-check',
                title: 'nav.status_check',
                subtitle: 'nav.system_health',
                type: 'basic',
                icon: 'heroicons_outline:check-circle',
                link: '/smart-monitor/status-check',
            },
            {
                id: 'incidents',
                title: 'nav.incidents',
                subtitle: 'nav.active_incidents',
                type: 'basic',
                icon: 'heroicons_outline:exclamation-triangle',
                link: '/smart-monitor/incidents',
            },
            {
                id: 'webhooks',
                title: 'nav.webhooks',
                subtitle: 'nav.webhooks_subtitle',
                type: 'basic',
                icon: 'heroicons_outline:link',
                link: '/smart-monitor/webhooks',
            },
        ],
    },
    {
        id: 'smart-tools',
        title: 'nav.smart_tools',
        type: 'collapsable',
        icon: 'heroicons_outline:wrench-screwdriver',
        children: [
            {
                id: 'smart-reduce',
                title: 'nav.smart_reduce',
                subtitle: 'nav.resize_compress_images',
                type: 'basic',
                icon: 'heroicons_outline:photo',
                link: '/smart-tools/smart-reduce',
            },
        ],
    },
    // {
    //   id: 'zelf-id',
    //   title: 'Zelf ID',
    //   type: 'basic',
    //   icon: 'heroicons_outline:identification',
    //   link: '/zelf-id',
    // },
];
