import { Injectable } from "@angular/core";

export interface CountryOption {
    name: string;
    code: string;
    country: string;
}

@Injectable({
    providedIn: "root",
})
export class CountryService {
    private _countryMap = new Map<string, CountryOption>();

    constructor() {
        this.countries.forEach((country) => {
            if (this._countryMap.has(country.country)) return;

            this._countryMap.set(country.country, country);
        });
    }

    get countries(): CountryOption[] {
        return [
            { name: "country_name.world", code: "world", country: "World" },
            { name: "country_name.afghanistan", code: "af", country: "Afghanistan" },
            { name: "country_name.albania", code: "al", country: "Albania" },
            { name: "country_name.algeria", code: "dz", country: "Algeria" },
            { name: "country_name.andorra", code: "ad", country: "Andorra" },
            { name: "country_name.angola", code: "ao", country: "Angola" },
            { name: "country_name.antigua_and_barbuda", code: "ag", country: "Antigua and Barbuda" },
            { name: "country_name.argentina", code: "ar", country: "Argentina" },
            { name: "country_name.armenia", code: "am", country: "Armenia" },
            { name: "country_name.australia", code: "au", country: "Australia" },
            { name: "country_name.austria", code: "at", country: "Austria" },
            { name: "country_name.azerbaijan", code: "az", country: "Azerbaijan" },
            { name: "country_name.bahamas", code: "bs", country: "Bahamas" },
            { name: "country_name.bahrain", code: "bh", country: "Bahrain" },
            { name: "country_name.bangladesh", code: "bd", country: "Bangladesh" },
            { name: "country_name.barbados", code: "bb", country: "Barbados" },
            { name: "country_name.belarus", code: "by", country: "Belarus" },
            { name: "country_name.belgium", code: "be", country: "Belgium" },
            { name: "country_name.belize", code: "bz", country: "Belize" },
            { name: "country_name.benin", code: "bj", country: "Benin" },
            { name: "country_name.bhutan", code: "bt", country: "Bhutan" },
            { name: "country_name.bolivia", code: "bo", country: "Bolivia" },
            { name: "country_name.bosnia_and_herzegovina", code: "ba", country: "Bosnia and Herzegovina" },
            { name: "country_name.botswana", code: "bw", country: "Botswana" },
            { name: "country_name.brazil", code: "br", country: "Brazil" },
            { name: "country_name.brunei", code: "bn", country: "Brunei" },
            { name: "country_name.bulgaria", code: "bg", country: "Bulgaria" },
            { name: "country_name.burkina_faso", code: "bf", country: "Burkina Faso" },
            { name: "country_name.burundi", code: "bi", country: "Burundi" },
            { name: "country_name.cambodia", code: "kh", country: "Cambodia" },
            { name: "country_name.cameroon", code: "cm", country: "Cameroon" },
            { name: "country_name.canada", code: "ca", country: "Canada" },
            { name: "country_name.cape_verde", code: "cv", country: "Cape Verde" },
            { name: "country_name.central_african_republic", code: "cf", country: "Central African Republic" },
            { name: "country_name.chad", code: "td", country: "Chad" },
            { name: "country_name.chile", code: "cl", country: "Chile" },
            { name: "country_name.china", code: "cn", country: "China" },
            { name: "country_name.colombia", code: "co", country: "Colombia" },
            { name: "country_name.comoros", code: "km", country: "Comoros" },
            { name: "country_name.congo", code: "cg", country: "Congo" },
            { name: "country_name.costa_rica", code: "cr", country: "Costa Rica" },
            { name: "country_name.croatia", code: "hr", country: "Croatia" },
            { name: "country_name.cuba", code: "cu", country: "Cuba" },
            { name: "country_name.cyprus", code: "cy", country: "Cyprus" },
            { name: "country_name.czech_republic", code: "cz", country: "Czech Republic" },
            { name: "country_name.denmark", code: "dk", country: "Denmark" },
            { name: "country_name.djibouti", code: "dj", country: "Djibouti" },
            { name: "country_name.dominica", code: "dm", country: "Dominica" },
            { name: "country_name.dominican_republic", code: "do", country: "Dominican Republic" },
            { name: "country_name.ecuador", code: "ec", country: "Ecuador" },
            { name: "country_name.egypt", code: "eg", country: "Egypt" },
            { name: "country_name.el_salvador", code: "sv", country: "El Salvador" },
            { name: "country_name.equatorial_guinea", code: "gq", country: "Equatorial Guinea" },
            { name: "country_name.eritrea", code: "er", country: "Eritrea" },
            { name: "country_name.estonia", code: "ee", country: "Estonia" },
            { name: "country_name.eswatini", code: "sz", country: "Eswatini" },
            { name: "country_name.ethiopia", code: "et", country: "Ethiopia" },
            { name: "country_name.fiji", code: "fj", country: "Fiji" },
            { name: "country_name.finland", code: "fi", country: "Finland" },
            { name: "country_name.france", code: "fr", country: "France" },
            { name: "country_name.gabon", code: "ga", country: "Gabon" },
            { name: "country_name.gambia", code: "gm", country: "Gambia" },
            { name: "country_name.georgia", code: "ge", country: "Georgia" },
            { name: "country_name.germany", code: "de", country: "Germany" },
            { name: "country_name.ghana", code: "gh", country: "Ghana" },
            { name: "country_name.greece", code: "gr", country: "Greece" },
            { name: "country_name.grenada", code: "gd", country: "Grenada" },
            { name: "country_name.guatemala", code: "gt", country: "Guatemala" },
            { name: "country_name.guinea", code: "gn", country: "Guinea" },
            { name: "country_name.guinea_bissau", code: "gw", country: "Guinea-Bissau" },
            { name: "country_name.guyana", code: "gy", country: "Guyana" },
            { name: "country_name.haiti", code: "ht", country: "Haiti" },
            { name: "country_name.honduras", code: "hn", country: "Honduras" },
            { name: "country_name.hungary", code: "hu", country: "Hungary" },
            { name: "country_name.iceland", code: "is", country: "Iceland" },
            { name: "country_name.india", code: "in", country: "India" },
            { name: "country_name.indonesia", code: "id", country: "Indonesia" },
            { name: "country_name.iran", code: "ir", country: "Iran" },
            { name: "country_name.iraq", code: "iq", country: "Iraq" },
            { name: "country_name.ireland", code: "ie", country: "Ireland" },
            { name: "country_name.israel", code: "il", country: "Israel" },
            { name: "country_name.italy", code: "it", country: "Italy" },
            { name: "country_name.jamaica", code: "jm", country: "Jamaica" },
            { name: "country_name.japan", code: "jp", country: "Japan" },
            { name: "country_name.jordan", code: "jo", country: "Jordan" },
            { name: "country_name.kazakhstan", code: "kz", country: "Kazakhstan" },
            { name: "country_name.kenya", code: "ke", country: "Kenya" },
            { name: "country_name.kiribati", code: "ki", country: "Kiribati" },
            { name: "country_name.kuwait", code: "kw", country: "Kuwait" },
            { name: "country_name.kyrgyzstan", code: "kg", country: "Kyrgyzstan" },
            { name: "country_name.laos", code: "la", country: "Laos" },
            { name: "country_name.latvia", code: "lv", country: "Latvia" },
            { name: "country_name.lebanon", code: "lb", country: "Lebanon" },
            { name: "country_name.lesotho", code: "ls", country: "Lesotho" },
            { name: "country_name.liberia", code: "lr", country: "Liberia" },
            { name: "country_name.libya", code: "ly", country: "Libya" },
            { name: "country_name.liechtenstein", code: "li", country: "Liechtenstein" },
            { name: "country_name.lithuania", code: "lt", country: "Lithuania" },
            { name: "country_name.luxembourg", code: "lu", country: "Luxembourg" },
            { name: "country_name.madagascar", code: "mg", country: "Madagascar" },
            { name: "country_name.malawi", code: "mw", country: "Malawi" },
            { name: "country_name.malaysia", code: "my", country: "Malaysia" },
            { name: "country_name.maldives", code: "mv", country: "Maldives" },
            { name: "country_name.mali", code: "ml", country: "Mali" },
            { name: "country_name.malta", code: "mt", country: "Malta" },
            { name: "country_name.marshall_islands", code: "mh", country: "Marshall Islands" },
            { name: "country_name.mauritania", code: "mr", country: "Mauritania" },
            { name: "country_name.mauritius", code: "mu", country: "Mauritius" },
            { name: "country_name.mexico", code: "mx", country: "Mexico" },
            { name: "country_name.micronesia", code: "fm", country: "Micronesia" },
            { name: "country_name.moldova", code: "md", country: "Moldova" },
            { name: "country_name.monaco", code: "mc", country: "Monaco" },
            { name: "country_name.mongolia", code: "mn", country: "Mongolia" },
            { name: "country_name.montenegro", code: "me", country: "Montenegro" },
            { name: "country_name.morocco", code: "ma", country: "Morocco" },
            { name: "country_name.mozambique", code: "mz", country: "Mozambique" },
            { name: "country_name.myanmar", code: "mm", country: "Myanmar" },
            { name: "country_name.namibia", code: "na", country: "Namibia" },
            { name: "country_name.nauru", code: "nr", country: "Nauru" },
            { name: "country_name.nepal", code: "np", country: "Nepal" },
            { name: "country_name.netherlands", code: "nl", country: "Netherlands" },
            { name: "country_name.new_zealand", code: "nz", country: "New Zealand" },
            { name: "country_name.nicaragua", code: "ni", country: "Nicaragua" },
            { name: "country_name.niger", code: "ne", country: "Niger" },
            { name: "country_name.nigeria", code: "ng", country: "Nigeria" },
            { name: "country_name.north_korea", code: "kp", country: "North Korea" },
            { name: "country_name.north_macedonia", code: "mk", country: "North Macedonia" },
            { name: "country_name.norway", code: "no", country: "Norway" },
            { name: "country_name.oman", code: "om", country: "Oman" },
            { name: "country_name.pakistan", code: "pk", country: "Pakistan" },
            { name: "country_name.palau", code: "pw", country: "Palau" },
            { name: "country_name.palestine", code: "ps", country: "Palestine" },
            { name: "country_name.panama", code: "pa", country: "Panama" },
            { name: "country_name.papua_new_guinea", code: "pg", country: "Papua New Guinea" },
            { name: "country_name.paraguay", code: "py", country: "Paraguay" },
            { name: "country_name.peru", code: "pe", country: "Peru" },
            { name: "country_name.philippines", code: "ph", country: "Philippines" },
            { name: "country_name.poland", code: "pl", country: "Poland" },
            { name: "country_name.portugal", code: "pt", country: "Portugal" },
            { name: "country_name.qatar", code: "qa", country: "Qatar" },
            { name: "country_name.romania", code: "ro", country: "Romania" },
            { name: "country_name.russia", code: "ru", country: "Russia" },
            { name: "country_name.rwanda", code: "rw", country: "Rwanda" },
            { name: "country_name.saint_kitts_and_nevis", code: "kn", country: "Saint Kitts and Nevis" },
            { name: "country_name.saint_lucia", code: "lc", country: "Saint Lucia" },
            { name: "country_name.saint_vincent_and_the_grenadines", code: "vc", country: "Saint Vincent and the Grenadines" },
            { name: "country_name.samoa", code: "ws", country: "Samoa" },
            { name: "country_name.san_marino", code: "sm", country: "San Marino" },
            { name: "country_name.sao_tome_and_principe", code: "st", country: "Sao Tome and Principe" },
            { name: "country_name.saudi_arabia", code: "sa", country: "Saudi Arabia" },
            { name: "country_name.senegal", code: "sn", country: "Senegal" },
            { name: "country_name.serbia", code: "rs", country: "Serbia" },
            { name: "country_name.seychelles", code: "sc", country: "Seychelles" },
            { name: "country_name.sierra_leone", code: "sl", country: "Sierra Leone" },
            { name: "country_name.singapore", code: "sg", country: "Singapore" },
            { name: "country_name.slovakia", code: "sk", country: "Slovakia" },
            { name: "country_name.slovenia", code: "si", country: "Slovenia" },
            { name: "country_name.solomon_islands", code: "sb", country: "Solomon Islands" },
            { name: "country_name.somalia", code: "so", country: "Somalia" },
            { name: "country_name.south_africa", code: "za", country: "South Africa" },
            { name: "country_name.south_korea", code: "kr", country: "South Korea" },
            { name: "country_name.south_sudan", code: "ss", country: "South Sudan" },
            { name: "country_name.spain", code: "es", country: "Spain" },
            { name: "country_name.sri_lanka", code: "lk", country: "Sri Lanka" },
            { name: "country_name.sudan", code: "sd", country: "Sudan" },
            { name: "country_name.suriname", code: "sr", country: "Suriname" },
            { name: "country_name.sweden", code: "se", country: "Sweden" },
            { name: "country_name.switzerland", code: "ch", country: "Switzerland" },
            { name: "country_name.syria", code: "sy", country: "Syria" },
            { name: "country_name.taiwan", code: "tw", country: "Taiwan" },
            { name: "country_name.tajikistan", code: "tj", country: "Tajikistan" },
            { name: "country_name.tanzania", code: "tz", country: "Tanzania" },
            { name: "country_name.thailand", code: "th", country: "Thailand" },
            { name: "country_name.timor_leste", code: "tl", country: "Timor-Leste" },
            { name: "country_name.togo", code: "tg", country: "Togo" },
            { name: "country_name.tonga", code: "to", country: "Tonga" },
            { name: "country_name.trinidad_and_tobago", code: "tt", country: "Trinidad and Tobago" },
            { name: "country_name.tunisia", code: "tn", country: "Tunisia" },
            { name: "country_name.turkey", code: "tr", country: "Turkey" },
            { name: "country_name.turkmenistan", code: "tm", country: "Turkmenistan" },
            { name: "country_name.tuvalu", code: "tv", country: "Tuvalu" },
            { name: "country_name.uganda", code: "ug", country: "Uganda" },
            { name: "country_name.ukraine", code: "ua", country: "Ukraine" },
            { name: "country_name.united_arab_emirates", code: "ae", country: "United Arab Emirates" },
            { name: "country_name.united_kingdom", code: "gb", country: "United Kingdom" },
            { name: "country_name.united_states", code: "us", country: "United States" },
            { name: "country_name.uruguay", code: "uy", country: "Uruguay" },
            { name: "country_name.uzbekistan", code: "uz", country: "Uzbekistan" },
            { name: "country_name.vanuatu", code: "vu", country: "Vanuatu" },
            { name: "country_name.venezuela", code: "ve", country: "Venezuela" },
            { name: "country_name.vietnam", code: "vn", country: "Vietnam" },
            { name: "country_name.yemen", code: "ye", country: "Yemen" },
            { name: "country_name.zambia", code: "zm", country: "Zambia" },
            { name: "country_name.zimbabwe", code: "zw", country: "Zimbabwe" },
        ];
    }
}
