/**
 * Smart Check API catalogue for support tickets.
 * Keep aligned with verifik-client-panel `SupportTicketService.smartCheckApis` when APIs change.
 */

export type SupportTicketSmartCheckApiType = 'identity' | 'vehicle' | 'business' | 'background';

export interface SupportTicketSmartCheckApi {
    type: SupportTicketSmartCheckApiType | string;
    value: string;
    /** Legacy client-panel translation key segment; picker uses appFeatures.<value>.title in Smart-Agent. */
    label: string;
    endpoint?: string;
    country?: string;
}

export type SupportTicketSmartCheckApiTypesOption = {
    value: SupportTicketSmartCheckApiType;
    labelKey: string;
};

export const SUPPORT_TICKET_API_TYPE_OPTIONS: SupportTicketSmartCheckApiTypesOption[] = [
    { value: 'identity', labelKey: 'supportTickets.quickChat.createDialog.apiTypes.identity' },
    { value: 'vehicle', labelKey: 'supportTickets.quickChat.createDialog.apiTypes.vehicle' },
    { value: 'business', labelKey: 'supportTickets.quickChat.createDialog.apiTypes.business' },
    { value: 'background', labelKey: 'supportTickets.quickChat.createDialog.apiTypes.background' },
];

export const SUPPORT_TICKET_SMARTCHECK_APIS: SupportTicketSmartCheckApi[] = [
            // Identity APIs
            {
                type: "identity",
                value: "argentina_api_identity_lookup",
                label: "data-api.argentina_api_identity_lookup",
                endpoint: "POST /v2/ar/cedula",
                country: "Argentina",
            },
            {
                type: "identity",
                value: "bolivia_api_identity_lookup",
                label: "data-api.bolivia_api_identity_lookup",
                endpoint: "POST /v2/bo/cedula",
                country: "Bolivia",
            },
            {
                type: "identity",
                value: "brasil_api_identity_lookup",
                label: "data-api.brasil_api_identity_lookup",
                endpoint: "POST /v2/br/cpf",
                country: "Brasil",
            },
            {
                type: "identity",
                value: "chile_api_identity_lookup",
                label: "data-api.chile_api_identity_lookup",
                endpoint: "POST /v2/cl/rut",
                country: "Chile",
            },
            {
                type: "identity",
                value: "colombia_api_identity_lookup",
                label: "data-api.colombia_api_identity_lookup",
                endpoint: "POST /v2/co/cedula",
                country: "Colombia",
            },
            {
                type: "identity",
                value: "colombia_api_identity_lookup_extra",
                label: "data-api.colombia_api_identity_lookup_extra",
                endpoint: "POST /v2/co/cedula-extra",
                country: "Colombia",
            },
            {
                type: "identity",
                value: "colombia_api_identity_pep_foreigner_id",
                label: "data-api.colombia_api_identity_pep_foreigner_id",
                endpoint: "POST /v2/co/pep",
                country: "Colombia",
            },
            {
                type: "identity",
                value: "colombia_api_identity_ce_foreigner_id",
                label: "data-api.colombia_api_identity_ce_foreigner_id",
                endpoint: "POST /v2/co/ce",
                country: "Colombia",
            },
            {
                type: "identity",
                value: "colombia_special_api_police_identity_lookup",
                label: "data-api.colombia_special_api_police_identity_lookup",
                endpoint: "POST /v2/co/police",
                country: "Colombia",
            },
            {
                type: "identity",
                value: "costarica_api_identity_lookup",
                label: "data-api.costarica_api_identity_lookup",
                endpoint: "POST /v2/cr/cedula",
                country: "Costa Rica",
            },
            {
                type: "identity",
                value: "ecuador_api_identity_lookup",
                label: "data-api.ecuador_api_identity_lookup",
                endpoint: "POST /v2/ec/cedula",
                country: "Ecuador",
            },
            {
                type: "identity",
                value: "el_salvador_api_identity_lookup",
                label: "data-api.el_salvador_api_identity_lookup",
                endpoint: "POST /v2/sv/dui",
                country: "El Salvador",
            },
            {
                type: "identity",
                value: "guatemala_api_identity_lookup",
                label: "data-api.guatemala_api_identity_lookup",
                endpoint: "POST /v2/gt/dpi",
                country: "Guatemala",
            },
            {
                type: "identity",
                value: "guatemala_api_identity_lookup_extra",
                label: "data-api.guatemala_api_identity_lookup_extra",
                endpoint: "POST /v2/gt/dpi-extra",
                country: "Guatemala",
            },
            {
                type: "identity",
                value: "honduras_api_identity_lookup",
                label: "data-api.honduras_api_identity_lookup",
                endpoint: "POST /v2/hn/dni",
                country: "Honduras",
            },
            {
                type: "identity",
                value: "mexico_identity_lookup",
                label: "data-api.mexico_identity_lookup",
                endpoint: "POST /v2/mx/curp",
                country: "México",
            },
            {
                type: "identity",
                value: "panama_api_identity_lookup",
                label: "data-api.panama_api_identity_lookup",
                endpoint: "POST /v2/pa/cedula",
                country: "Panamá",
            },
            {
                type: "identity",
                value: "panama_api_identity_full_lookup",
                label: "data-api.panama_api_identity_full_lookup",
                endpoint: "POST /v2/pa/cedula-full",
                country: "Panamá",
            },
            {
                type: "identity",
                value: "paraguay_api_identity_lookup",
                label: "data-api.paraguay_api_identity_lookup",
                endpoint: "POST /v2/py/cedula",
                country: "Paraguay",
            },
            {
                type: "identity",
                value: "peru_identity_lookup",
                label: "data-api.peru_identity_lookup",
                endpoint: "POST /v2/pe/dni",
                country: "Perú",
            },
            {
                type: "identity",
                value: "peru_identity_extra_lookup",
                label: "data-api.peru_identity_extra_lookup",
                endpoint: "POST /v2/pe/dni-extra",
                country: "Perú",
            },
            {
                type: "identity",
                value: "peru_identity_extra_lookup_v3",
                label: "data-api.peru_identity_extra_lookup_v3",
                endpoint: "POST /v3/pe/dni-extra",
                country: "Perú",
            },
            {
                type: "identity",
                value: "peru_identity_lookup_v3",
                label: "data-api.peru_identity_lookup_v3",
                endpoint: "POST /v3/pe/dni",
                country: "Perú",
            },
            {
                type: "identity",
                value: "peru_identity_verify",
                label: "data-api.peru_identity_verify",
                endpoint: "POST /v2/pe/verify",
                country: "Perú",
            },
            {
                type: "identity",
                value: "republica_dominicana_api_citizen_lookup",
                label: "data-api.republica_dominicana_api_citizen_lookup",
                endpoint: "POST /v2/do/cedula",
                country: "República Dominicana",
            },
            {
                type: "identity",
                value: "spain_api_identity_lookup",
                label: "data-api.spain_api_identity_lookup",
                endpoint: "POST /v2/es/dni",
                country: "España",
            },
            {
                type: "identity",
                value: "uruguay_api_identity_lookup",
                label: "data-api.uruguay_api_identity_lookup",
                endpoint: "POST /v2/uy/cedula",
                country: "Uruguay",
            },
            {
                type: "identity",
                value: "venezuela_api_identity_lookup",
                label: "data-api.venezuela_api_identity_lookup",
                endpoint: "POST /v2/ve/cedula",
                country: "Venezuela",
            },
            {
                type: "identity",
                value: "venezuela_foreigner_api",
                label: "data-api.venezuela_foreigner_api",
                endpoint: "POST /v2/ve/foreigner",
                country: "Venezuela",
            },
            {
                type: "identity",
                value: "chile_api_validate",
                label: "data-api.chile_api_validate",
                endpoint: "POST /v2/cl/validate",
                country: "Chile",
            },
            {
                type: "identity",
                value: "chile_api_taxpayer_lookup",
                label: "data-api.chile_api_taxpayer_lookup",
                endpoint: "POST /v2/cl/taxpayer",
                country: "Chile",
            },
            {
                type: "identity",
                value: "consultar_cedula_ecuador",
                label: "data-api.consultar_cedula_ecuador",
                endpoint: "GET /v1/ec/cedula",
                country: "Ecuador",
            },
            {
                type: "identity",
                value: "consultar_cedula_peru",
                label: "data-api.consultar_cedula_peru",
                endpoint: "GET /v1/pe/cedula",
                country: "Perú",
            },
            {
                type: "identity",
                value: "consultar_nombre_argentino",
                label: "data-api.consultar_nombre_argentino",
                endpoint: "GET /v1/ar/nombre",
                country: "Argentina",
            },
            {
                type: "identity",
                value: "consultar_nombre_brasileño",
                label: "data-api.consultar_nombre_brasileño",
                endpoint: "GET /v1/br/nombre",
                country: "Brasil",
            },
            {
                type: "identity",
                value: "consultar_nombre_chileno",
                label: "data-api.consultar_nombre_chileno",
                endpoint: "GET /v1/cl/nombre",
                country: "Chile",
            },
            {
                type: "identity",
                value: "consultar_nombre_colombiano",
                label: "data-api.consultar_nombre_colombiano",
                endpoint: "GET /v1/co/nombre",
                country: "Colombia",
            },
            {
                type: "identity",
                value: "consultar_nombre_mexicano",
                label: "data-api.consultar_nombre_mexicano",
                endpoint: "GET /v1/mx/nombre",
                country: "México",
            },
            {
                type: "identity",
                value: "consultar_nombre_panama",
                label: "data-api.consultar_nombre_panama",
                endpoint: "GET /v1/pa/nombre",
                country: "Panamá",
            },
            {
                type: "identity",
                value: "consultar_nombre_panama_extra",
                label: "data-api.consultar_nombre_panama_extra",
                endpoint: "GET /v1/pa/nombre-extra",
                country: "Panamá",
            },
            {
                type: "identity",
                value: "consultar_nombre_venezolano",
                label: "data-api.consultar_nombre_venezolano",
                endpoint: "GET /v1/ve/nombre",
                country: "Venezuela",
            },
            {
                type: "identity",
                value: "usa_api_ssn",
                label: "data-api.usa_api_ssn",
                endpoint: "POST /v2/us/ssn",
                country: "USA",
            },
            {
                type: "identity",
                value: "verificar_ssn_usa",
                label: "data-api.verificar_ssn_usa",
                endpoint: "GET /v1/us/ssn/verify",
                country: "USA",
            },
            {
                type: "identity",
                value: "world_api_passport",
                label: "data-api.world_api_passport",
                endpoint: "POST /v2/world/passport",
                country: "Global",
            },
            {
                type: "identity",
                value: "world_api_passport_entries",
                label: "data-api.world_api_passport_entries",
                endpoint: "POST /v2/world/passport-entries",
                country: "Global",
            },
            {
                type: "identity",
                value: "us_api_passport_entries",
                label: "data-api.us_api_passport_entries",
                endpoint: "POST /v2/us/passport-entries",
                country: "USA",
            },

            // Vehicle APIs
            {
                type: "vehicle",
                value: "api_autodata_enginer_code",
                label: "data-api.api_autodata_enginer_code",
                endpoint: "/v2/autodata/engine-code",
                country: "Global",
            },
            {
                type: "vehicle",
                value: "api_autodata_enginer",
                label: "data-api.api_autodata_enginer",
                endpoint: "/v2/autodata/engine",
                country: "Global",
            },
            {
                type: "vehicle",
                value: "api_autodata_manufacturers",
                label: "data-api.api_autodata_manufacturers",
                endpoint: "/v2/autodata/manufacturers",
                country: "Global",
            },
            {
                type: "vehicle",
                value: "api_autodata_selection",
                label: "data-api.api_autodata_selection",
                endpoint: "/v2/autodata/selection",
                country: "Global",
            },
            {
                type: "vehicle",
                value: "api_data_seheet_vehicle_br",
                label: "data-api.api_data_seheet_vehicle_br",
                endpoint: "/v2/br/vehicle-datasheet",
                country: "Brasil",
            },
            {
                type: "vehicle",
                value: "api_data_seheet_vehicle",
                label: "data-api.api_data_seheet_vehicle",
                endpoint: "/v2/vehicle/datasheet",
                country: "Global",
            },
            {
                type: "vehicle",
                value: "api_data_sheet_b",
                label: "data-api.api_data_sheet_b",
                endpoint: "/v2/vehicle/datasheet-b",
                country: "Global",
            },
            {
                type: "vehicle",
                value: "api_data_sheet_vehicle",
                label: "data-api.api_data_sheet_vehicle",
                endpoint: "/v2/vehicle/datasheet",
                country: "Global",
            },
            {
                type: "vehicle",
                value: "argentina_api_vehicle",
                label: "data-api.argentina_api_vehicle",
                endpoint: "/v2/ar/vehicle",
                country: "Argentina",
            },
            { type: "vehicle", value: "bolivia_api_vehicle", label: "data-api.bolivia_api_vehicle", endpoint: "/v2/bo/vehicle", country: "Bolivia" },
            { type: "vehicle", value: "brasil_api_vehicle", label: "data-api.brasil_api_vehicle", endpoint: "/v2/br/vehicle", country: "Brasil" },
            { type: "vehicle", value: "chile_api_vehicle", label: "data-api.chile_api_vehicle", endpoint: "/v2/cl/vehicle", country: "Chile" },
            {
                type: "vehicle",
                value: "colombia_api_vehicle",
                label: "data-api.colombia_api_vehicle",
                endpoint: "/v2/co/vehicle",
                country: "Colombia",
            },
            {
                type: "vehicle",
                value: "colombia_api_vehicle_complete",
                label: "data-api.colombia_api_vehicle_complete",
                endpoint: "/v2/co/vehicle-complete",
                country: "Colombia",
            },
            {
                type: "vehicle",
                value: "colombia_api_vehicle_complete_by_plate",
                label: "data-api.colombia_api_vehicle_complete_by_plate",
                endpoint: "/v2/co/vehicle-by-plate",
                country: "Colombia",
            },
            {
                type: "vehicle",
                value: "colombia_api_vehicle_complete_by_vin",
                label: "data-api.colombia_api_vehicle_complete_by_vin",
                endpoint: "/v2/co/vehicle-by-vin",
                country: "Colombia",
            },
            {
                type: "vehicle",
                value: "colombia_api_vehicle_complete_by_plate_simplified",
                label: "data-api.colombia_api_vehicle_complete_by_plate_simplified",
                endpoint: "/v2/co/vehicle-simplified",
                country: "Colombia",
            },
            {
                type: "vehicle",
                value: "colombia_api_vehicle_soat",
                label: "data-api.colombia_api_vehicle_soat",
                endpoint: "/v2/co/vehicle-soat",
                country: "Colombia",
            },
            {
                type: "vehicle",
                value: "colombia_api_vehicle_accidentality_bogota",
                label: "data-api.colombia_api_vehicle_accidentality_bogota",
                endpoint: "/v2/co/vehicle-accidents",
                country: "Colombia",
            },
            {
                type: "vehicle",
                value: "colombia_api_vehicle_tax",
                label: "data-api.colombia_api_vehicle_tax",
                endpoint: "/v2/co/vehicle-tax",
                country: "Colombia",
            },
            {
                type: "vehicle",
                value: "colombia_api_vehicle_valores_fasecolda_by_plate",
                label: "data-api.colombia_api_vehicle_valores_fasecolda_by_plate",
                endpoint: "/v2/co/fasecolda-plate",
                country: "Colombia",
            },
            {
                type: "vehicle",
                value: "colombia_api_vehicle_valores_fasecolda_by_code",
                label: "data-api.colombia_api_vehicle_valores_fasecolda_by_code",
                endpoint: "/v2/co/fasecolda-code",
                country: "Colombia",
            },
            {
                type: "vehicle",
                value: "colombia_api_vehicle_sinister_fasecolda_by_plate",
                label: "data-api.colombia_api_vehicle_sinister_fasecolda_by_plate",
                endpoint: "/v2/co/fasecolda-sinister",
                country: "Colombia",
            },
            {
                type: "vehicle",
                value: "colombia_api_pico_placa",
                label: "data-api.colombia_api_pico_placa",
                endpoint: "/v2/co/pico-placa",
                country: "Colombia",
            },
            {
                type: "vehicle",
                value: "costa_rica_api_vehicle",
                label: "data-api.costa_rica_api_vehicle",
                endpoint: "/v2/cr/vehicle",
                country: "Costa Rica",
            },
            { type: "vehicle", value: "ecuador_api_vehicle", label: "data-api.ecuador_api_vehicle", endpoint: "/v2/ec/vehicle", country: "Ecuador" },
            {
                type: "vehicle",
                value: "ecuador_api_vehicle_fines",
                label: "data-api.ecuador_api_vehicle_fines",
                endpoint: "/v2/ec/vehicle-fines",
                country: "Ecuador",
            },
            { type: "vehicle", value: "mexico_api_vehicle", label: "data-api.mexico_api_vehicle", endpoint: "/v2/mx/vehicle", country: "México" },
            { type: "vehicle", value: "panama_api_vehicle", label: "data-api.panama_api_vehicle", endpoint: "/v2/pa/vehicle", country: "Panamá" },
            {
                type: "vehicle",
                value: "paraguay_api_vehicle",
                label: "data-api.paraguay_api_vehicle",
                endpoint: "/v2/py/vehicle",
                country: "Paraguay",
            },
            { type: "vehicle", value: "peru_api_vehicle", label: "data-api.peru_api_vehicle", endpoint: "/v2/pe/vehicle", country: "Perú" },
            {
                type: "vehicle",
                value: "peru_api_vehicle_soat",
                label: "data-api.peru_api_vehicle_soat",
                endpoint: "/v2/pe/vehicle-soat",
                country: "Perú",
            },
            {
                type: "vehicle",
                value: "spain_api_vehicle_lookup",
                label: "data-api.spain_api_vehicle_lookup",
                endpoint: "/v2/es/vehicle",
                country: "España",
            },
            { type: "vehicle", value: "usa_api_vehicle", label: "data-api.usa_api_vehicle", endpoint: "/v2/us/vehicle", country: "USA" },
            {
                type: "vehicle",
                value: "usa_api_vehicle_lookup_by_vin",
                label: "data-api.usa_api_vehicle_lookup_by_vin",
                endpoint: "/v2/us/vehicle-vin",
                country: "USA",
            },
            {
                type: "vehicle",
                value: "consultar_vehicle_chile",
                label: "data-api.consultar_vehicle_chile",
                endpoint: "/v1/cl/vehicle",
                country: "Chile",
            },
            {
                type: "vehicle",
                value: "consultar_vehicle_ecuador",
                label: "data-api.consultar_vehicle_ecuador",
                endpoint: "/v1/ec/vehicle",
                country: "Ecuador",
            },
            {
                type: "vehicle",
                value: "consultar_vehicle_mexico",
                label: "data-api.consultar_vehicle_mexico",
                endpoint: "/v1/mx/vehicle",
                country: "México",
            },
            {
                type: "vehicle",
                value: "consultar_vehiculo_brasil",
                label: "data-api.consultar_vehiculo_brasil",
                endpoint: "/v1/br/vehicle",
                country: "Brasil",
            },
            {
                type: "vehicle",
                value: "consultar_vehiculo_placa_peru",
                label: "data-api.consultar_vehiculo_placa_peru",
                endpoint: "/v1/pe/vehicle-plate",
                country: "Perú",
            },
            {
                type: "vehicle",
                value: "consultar_vehiculo_placa_usa",
                label: "data-api.consultar_vehiculo_placa_usa",
                endpoint: "/v1/us/vehicle-plate",
                country: "USA",
            },
            {
                type: "vehicle",
                value: "consultar_vehiculo_soat_peru",
                label: "data-api.consultar_vehiculo_soat_peru",
                endpoint: "/v1/pe/vehicle-soat",
                country: "Perú",
            },
            { type: "vehicle", value: "consultar_vehiculo", label: "data-api.consultar_vehiculo", endpoint: "/v1/co/vehicle", country: "Colombia" },
            {
                type: "vehicle",
                value: "chile_api_driver_license",
                label: "data-api.chile_api_driver_license",
                endpoint: "/v2/cl/driver-license",
                country: "Chile",
            },
            { type: "vehicle", value: "colombia_api_driver", label: "data-api.colombia_api_driver", endpoint: "/v2/co/driver", country: "Colombia" },
            {
                type: "vehicle",
                value: "usa_api_driver_license_lookup",
                label: "data-api.usa_api_driver_license_lookup",
                endpoint: "/v2/us/driver-license",
                country: "USA",
            },
            {
                type: "vehicle",
                value: "usa_api_driver_license_lookup_georgia",
                label: "data-api.usa_api_driver_license_lookup_georgia",
                endpoint: "/v2/us/driver-license/georgia",
                country: "USA",
            },
            {
                type: "vehicle",
                value: "usa_api_driver_license_lookup_kansas",
                label: "data-api.usa_api_driver_license_lookup_kansas",
                endpoint: "/v2/us/driver-license/kansas",
                country: "USA",
            },
            {
                type: "vehicle",
                value: "canada_api_driver_license_alberta",
                label: "data-api.canada_api_driver_license_alberta",
                endpoint: "/v2/ca/driver-license/alberta",
                country: "Canadá",
            },
            {
                type: "vehicle",
                value: "canada_api_driver_license_ontario",
                label: "data-api.canada_api_driver_license_ontario",
                endpoint: "/v2/ca/driver-license/ontario",
                country: "Canadá",
            },
            {
                type: "vehicle",
                value: "canada_api_driver_license_quebec",
                label: "data-api.canada_api_driver_license_quebec",
                endpoint: "/v2/ca/driver-license/quebec",
                country: "Canadá",
            },
            {
                type: "vehicle",
                value: "canada_api_driver_license_british-columbia",
                label: "data-api.canada_api_driver_license_british-columbia",
                endpoint: "/v2/ca/driver-license/bc",
                country: "Canadá",
            },
            {
                type: "vehicle",
                value: "consultar-license-florida",
                label: "data-api.consultar-license-florida",
                endpoint: "/v1/us/driver-license/florida",
                country: "USA",
            },

            // Business APIs
            {
                type: "business",
                value: "argentina_api_company_lookup",
                label: "data-api.argentina_api_company_lookup",
                endpoint: "/v2/ar/company",
                country: "Argentina",
            },
            {
                type: "business",
                value: "bolivia_api_business_lookup",
                label: "data-api.bolivia_api_business_lookup",
                endpoint: "/v2/bo/company",
                country: "Bolivia",
            },
            {
                type: "business",
                value: "brasil_api_company_lookup",
                label: "data-api.brasil_api_company_lookup",
                endpoint: "/v2/br/company",
                country: "Brasil",
            },
            { type: "business", value: "canada_api_company", label: "data-api.canada_api_company", endpoint: "/v2/ca/company", country: "Canadá" },
            {
                type: "business",
                value: "chile_api_business_lookup",
                label: "data-api.chile_api_business_lookup",
                endpoint: "/v2/cl/company",
                country: "Chile",
            },
            { type: "business", value: "colombia_api_rues", label: "data-api.colombia_api_rues", endpoint: "/v2/co/rues", country: "Colombia" },
            { type: "business", value: "colombia_api_rues_v3", label: "data-api.colombia_api_rues_v3", endpoint: "/v3/co/rues", country: "Colombia" },
            {
                type: "business",
                value: "colombia_api_rues_full_v3",
                label: "data-api.colombia_api_rues_full_v3",
                endpoint: "/v3/co/rues-full",
                country: "Colombia",
            },
            { type: "business", value: "colombia_api_dian", label: "data-api.colombia_api_dian", endpoint: "/v2/co/dian", country: "Colombia" },
            {
                type: "business",
                value: "colombia_api_dian_invoicer",
                label: "data-api.colombia_api_dian_invoicer",
                endpoint: "/v2/co/dian-invoicer",
                country: "Colombia",
            },
            {
                type: "business",
                value: "costa_rica_api_business_lookup",
                label: "data-api.costa_rica_api_business_lookup",
                endpoint: "/v2/cr/company",
                country: "Costa Rica",
            },
            {
                type: "business",
                value: "ecuador_api_company_lookup",
                label: "data-api.ecuador_api_company_lookup",
                endpoint: "/v2/ec/company",
                country: "Ecuador",
            },
            { type: "business", value: "mexico_api_company", label: "data-api.mexico_api_company", endpoint: "/v2/mx/company", country: "México" },
            {
                type: "business",
                value: "panama_api_business_lookup",
                label: "data-api.panama_api_business_lookup",
                endpoint: "/v2/pa/company",
                country: "Panamá",
            },
            {
                type: "business",
                value: "paraguay_api_business_lookup",
                label: "data-api.paraguay_api_business_lookup",
                endpoint: "/v2/py/company",
                country: "Paraguay",
            },
            {
                type: "business",
                value: "peru_api_company_lookup",
                label: "data-api.peru_api_company_lookup",
                endpoint: "/v2/pe/company",
                country: "Perú",
            },
            {
                type: "business",
                value: "spain_api_company_lookup",
                label: "data-api.spain_api_company_lookup",
                endpoint: "/v2/es/company",
                country: "España",
            },
            { type: "business", value: "usa_api_company", label: "data-api.usa_api_company", endpoint: "/v2/us/company", country: "USA" },
            {
                type: "business",
                value: "api_colombia_contracts",
                label: "data-api.api_colombia_contracts",
                endpoint: "/v2/co/contracts",
                country: "Colombia",
            },
            {
                type: "business",
                value: "colombia_api_lawyers",
                label: "data-api.colombia_api_lawyers",
                endpoint: "/v2/co/lawyers",
                country: "Colombia",
            },
            {
                type: "business",
                value: "colombia_api_lawyers_certificate",
                label: "data-api.colombia_api_lawyers_certificate",
                endpoint: "/v2/co/lawyers-certificate",
                country: "Colombia",
            },
            {
                type: "business",
                value: "consultar_empresa_brasil",
                label: "data-api.consultar_empresa_brasil",
                endpoint: "/v1/br/company",
                country: "Brasil",
            },
            {
                type: "business",
                value: "consultar_empresa_ecuador",
                label: "data-api.consultar_empresa_ecuador",
                endpoint: "/v1/ec/company",
                country: "Ecuador",
            },
            {
                type: "business",
                value: "consultar_empresa_peru",
                label: "data-api.consultar_empresa_peru",
                endpoint: "/v1/pe/company",
                country: "Perú",
            },

            // Background APIs
            {
                type: "background",
                value: "background_check",
                label: "data-api.background_check",
                endpoint: "/v2/background-check",
                country: "Global",
            },
            {
                type: "background",
                value: "brasil_api_criminal_history",
                label: "data-api.brasil_api_criminal_history",
                endpoint: "/v2/br/criminal",
                country: "Brasil",
            },
            {
                type: "background",
                value: "colombia_api_criminal_history",
                label: "data-api.colombia_api_criminal_history",
                endpoint: "/v2/co/criminal",
                country: "Colombia",
            },
            {
                type: "background",
                value: "ecuador_api_criminal_history",
                label: "data-api.ecuador_api_criminal_history",
                endpoint: "/v2/ec/criminal",
                country: "Ecuador",
            },
            {
                type: "background",
                value: "colombia_special_api_police_identity_lookup",
                label: "data-api.colombia_special_api_police_identity_lookup",
                endpoint: "/v2/co/police",
                country: "Colombia",
            },
            {
                type: "background",
                value: "colombia_api_judicial_records",
                label: "data-api.colombia_api_judicial_records",
                endpoint: "/v2/co/judicial-records",
                country: "Colombia",
            },
            {
                type: "background",
                value: "colombia_api_judicial_processes",
                label: "data-api.colombia_api_judicial_processes",
                endpoint: "/v2/co/judicial-processes",
                country: "Colombia",
            },
            {
                type: "background",
                value: "colombia_api_judicial_process_details",
                label: "data-api.colombia_api_judicial_process_details",
                endpoint: "/v2/co/judicial-details",
                country: "Colombia",
            },
            {
                type: "background",
                value: "colombia_api_delinquent_debtors",
                label: "data-api.colombia_api_delinquent_debtors",
                endpoint: "/v2/co/delinquent-debtors",
                country: "Colombia",
            },
            {
                type: "background",
                value: "colombia_api_military_situation",
                label: "data-api.colombia_api_military_situation",
                endpoint: "/v2/co/military",
                country: "Colombia",
            },
            {
                type: "background",
                value: "colombia_api_police_rnmc",
                label: "data-api.colombia_api_police_rnmc",
                endpoint: "/v2/co/police-rnmc",
                country: "Colombia",
            },
            { type: "background", value: "colombia_pep_lookup", label: "data-api.colombia_pep_lookup", endpoint: "/v2/co/pep", country: "Colombia" },
            {
                type: "background",
                value: "colombia_api_affiliations",
                label: "data-api.colombia_api_affiliations",
                endpoint: "/v2/co/affiliations",
                country: "Colombia",
            },
            {
                type: "background",
                value: "colombia_api_rethus",
                label: "data-api.colombia_api_rethus",
                endpoint: "/v2/co/rethus",
                country: "Colombia",
            },
            { type: "background", value: "colombia_api_sena", label: "data-api.colombia_api_sena", endpoint: "/v2/co/sena", country: "Colombia" },
            {
                type: "background",
                value: "colombia_api_sisconmp",
                label: "data-api.colombia_api_sisconmp",
                endpoint: "/v2/co/sisconmp",
                country: "Colombia",
            },
            {
                type: "background",
                value: "colombia_api_min_trabajo",
                label: "data-api.colombia_api_min_trabajo",
                endpoint: "/v2/co/min-trabajo",
                country: "Colombia",
            },
            {
                type: "background",
                value: "colombia_api_contraloria_certificate",
                label: "data-api.colombia_api_contraloria_certificate",
                endpoint: "/v2/co/contraloria",
                country: "Colombia",
            },
            {
                type: "background",
                value: "colombia_api_registraduria_certificate",
                label: "data-api.colombia_api_registraduria_certificate",
                endpoint: "/v2/co/registraduria",
                country: "Colombia",
            },
            {
                type: "background",
                value: "colombia_api_registraduria_voting",
                label: "data-api.colombia_api_registraduria_voting",
                endpoint: "/v2/co/voting",
                country: "Colombia",
            },
            {
                type: "background",
                value: "colombia_api_runt_owners",
                label: "data-api.colombia_api_runt_owners",
                endpoint: "/v2/co/runt-owners",
                country: "Colombia",
            },
            {
                type: "background",
                value: "colombia_api_simit_agreements",
                label: "data-api.colombia_api_simit_agreements",
                endpoint: "/v2/co/simit-agreements",
                country: "Colombia",
            },
            {
                type: "background",
                value: "colombia_api_simit_plate",
                label: "data-api.colombia_api_simit_plate",
                endpoint: "/v2/co/simit-plate",
                country: "Colombia",
            },
            {
                type: "background",
                value: "colombia_api_simit_suspensions",
                label: "data-api.colombia_api_simit_suspensions",
                endpoint: "/v2/co/simit-suspensions",
                country: "Colombia",
            },
            {
                type: "background",
                value: "colombia_api_vehicle_accidentality_bogota",
                label: "data-api.colombia_api_vehicle_accidentality_bogota",
                endpoint: "/v2/co/accidents-bogota",
                country: "Colombia",
            },
            {
                type: "background",
                value: "colombia_api_vehicle_tax",
                label: "data-api.colombia_api_vehicle_tax",
                endpoint: "/v2/co/vehicle-tax",
                country: "Colombia",
            },
            {
                type: "background",
                value: "colombia_api_vehicle_fines_bogota",
                label: "data-api.colombia_api_vehicle_fines_bogota",
                endpoint: "/v2/co/fines-bogota",
                country: "Colombia",
            },
            {
                type: "background",
                value: "colombia_api_vehicle_fines_medellin",
                label: "data-api.colombia_api_vehicle_fines_medellin",
                endpoint: "/v2/co/fines-medellin",
                country: "Colombia",
            },
            { type: "background", value: "world_api_dea", label: "data-api.world_api_dea", endpoint: "/v2/world/dea", country: "Global" },
            {
                type: "background",
                value: "world_api_dea_by_name",
                label: "data-api.world_api_dea_by_name",
                endpoint: "/v2/world/dea/name",
                country: "Global",
            },
            { type: "background", value: "world_api_europol", label: "data-api.world_api_europol", endpoint: "/v2/world/europol", country: "Global" },
            {
                type: "background",
                value: "world_api_europol_by_name",
                label: "data-api.world_api_europol_by_name",
                endpoint: "/v2/world/europol/name",
                country: "Global",
            },
            { type: "background", value: "world_api_fbi", label: "data-api.world_api_fbi", endpoint: "/v2/world/fbi", country: "Global" },
            {
                type: "background",
                value: "world_api_fbi_by_name",
                label: "data-api.world_api_fbi_by_name",
                endpoint: "/v2/world/fbi/name",
                country: "Global",
            },
            {
                type: "background",
                value: "world_api_interpol",
                label: "data-api.world_api_interpol",
                endpoint: "/v2/world/interpol",
                country: "Global",
            },
            {
                type: "background",
                value: "world_api_interpol_by_name",
                label: "data-api.world_api_interpol_by_name",
                endpoint: "/v2/world/interpol/name",
                country: "Global",
            },
            { type: "background", value: "world_api_ofac", label: "data-api.world_api_ofac", endpoint: "/v2/world/ofac", country: "Global" },
            {
                type: "background",
                value: "world_api_ofac_by_name",
                label: "data-api.world_api_ofac_by_name",
                endpoint: "/v2/world/ofac/name",
                country: "Global",
            },
            { type: "background", value: "world_api_onu", label: "data-api.world_api_onu", endpoint: "/v2/world/onu", country: "Global" },
            {
                type: "background",
                value: "world_api_onu_by_name",
                label: "data-api.world_api_onu_by_name",
                endpoint: "/v2/world/onu/name",
                country: "Global",
            },
            {
                type: "background",
                value: "consultar_abogados",
                label: "data-api.consultar_abogados",
                endpoint: "/v1/co/lawyers",
                country: "Colombia",
            },
            {
                type: "background",
                value: "consultar_antecedentes",
                label: "data-api.consultar_antecedentes",
                endpoint: "/v1/co/background",
                country: "Colombia",
            },
            {
                type: "background",
                value: "consultar_comparendos",
                label: "data-api.consultar_comparendos",
                endpoint: "/v1/co/comparendos",
                country: "Colombia",
            },
            {
                type: "background",
                value: "consultar_conductor",
                label: "data-api.consultar_conductor",
                endpoint: "/v1/co/driver",
                country: "Colombia",
            },
            {
                type: "background",
                value: "consultar_detalle_procesos",
                label: "data-api.consultar_detalle_procesos",
                endpoint: "/v1/co/process-details",
                country: "Colombia",
            },
            {
                type: "background",
                value: "consultar_deudores_moroso",
                label: "data-api.consultar_deudores_moroso",
                endpoint: "/v1/co/debtors",
                country: "Colombia",
            },
            {
                type: "background",
                value: "consultar_procesos_judiciales",
                label: "data-api.consultar_procesos_judiciales",
                endpoint: "/v1/co/judicial",
                country: "Colombia",
            },
            {
                type: "background",
                value: "consultar_procesos_judiciales_expedientes",
                label: "data-api.consultar_procesos_judiciales_expedientes",
                endpoint: "/v1/co/judicial-files",
                country: "Colombia",
            },
            {
                type: "background",
                value: "consultar_situacion_militar",
                label: "data-api.consultar_situacion_militar",
                endpoint: "/v1/co/military",
                country: "Colombia",
            },
            {
                type: "background",
                value: "consultar_rethus_colombia",
                label: "data-api.consultar_rethus_colombia",
                endpoint: "/v1/co/rethus",
                country: "Colombia",
            },
            { type: "background", value: "consultar_rues", label: "data-api.consultar_rues", endpoint: "/v1/co/rues", country: "Colombia" },
            { type: "background", value: "consultar_sena", label: "data-api.consultar_sena" },
            {
                type: "background",
                value: "consultar_simit_con_captcha",
                label: "data-api.consultar_simit_con_captcha",
            },
            { type: "background", value: "consultar_suspenciones", label: "data-api.consultar_suspenciones" },
            { type: "background", value: "consultar_vehicle_chile", label: "data-api.consultar_vehicle_chile" },
            { type: "background", value: "consultar_vehicle_ecuador", label: "data-api.consultar_vehicle_ecuador" },
            { type: "background", value: "consultar_vehicle_mexico", label: "data-api.consultar_vehicle_mexico" },
            { type: "background", value: "consultar_vehiculo_brasil", label: "data-api.consultar_vehiculo_brasil" },
            {
                type: "background",
                value: "consultar_vehiculo_placa_peru",
                label: "data-api.consultar_vehiculo_placa_peru",
            },
            {
                type: "background",
                value: "consultar_vehiculo_placa_usa",
                label: "data-api.consultar_vehiculo_placa_usa",
            },
            {
                type: "background",
                value: "consultar_vehiculo_soat_peru",
                label: "data-api.consultar_vehiculo_soat_peru",
            },
            { type: "background", value: "consultar_vehiculo", label: "data-api.consultar_vehiculo" },
            { type: "background", value: "world_api_covid", label: "data-api.world_api_covid" },
            { type: "background", value: "world_api_phone_lookup", label: "data-api.world_api_phone_lookup" },
            { type: "background", value: "ip-lookup", label: "data-api.ip-lookup" },
            { type: "background", value: "validate-document", label: "data-api.validate-document" },
];
